name: tablero_led
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  hive: ^2.2.3
  hive_generator: ^2.0.1
  http: ^1.2.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  wifi_iot: ^0.3.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba  
      
flutter:
  uses-material-design: true
